# Generated by Django 5.0 on 2023-12-07 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='shared_with',
            field=models.ManyToManyField(default=None, related_name='shared_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
